import { MoveLeft } from 'lucide-react';
import { LoginForm } from './_components/login-form';
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'KNAI login',
  description: 'Generated by create next app',
};

export default function LoginLayout() {
  return (
    <div className="bg-muted flex flex-col justify-center h-full">
      <div className="flex min-h-svh flex-col items-center justify-center p-6 md:p-10">
        <div className="w-full max-w-sm md:max-w-3xl flex flex-col gap-10">
          <Link href={'/'}>
            <MoveLeft
              size={40}
              className="bg-black p-2 rounded-full animate-bounce-horizontal text-white"
            />
          </Link>
          <LoginForm />
        </div>
      </div>
    </div>
  );
}
